ALTER TABLE guides
    DROP CONSTRAINT guides_user_id_fkey;

ALTER TABLE journal_entries
    DROP CONSTRAINT journal_entries_trip_id_fkey;

ALTER TABLE tour_purchases
    DROP CONSTRAINT tour_purchases_buyer_user_id_fkey;

ALTER TABLE tour_purchases
    DROP CONSTRAINT tour_purchases_tour_id_fkey;

ALTER TABLE tours
    DROP CONSTRAINT tours_guide_id_fkey;

ALTER TABLE trip_items
    DROP CONSTRAINT trip_items_trip_id_fkey;

ALTER TABLE trips
    DROP CONSTRAINT trips_user_id_fkey;

ALTER TABLE user_points
    DROP CONSTRAINT user_points_user_id_fkey;

ALTER TABLE user_roles
    DROP CONSTRAINT user_roles_role_id_fkey;

ALTER TABLE user_roles
    DROP CONSTRAINT user_roles_user_id_fkey;

ALTER TABLE visited_places
    DROP CONSTRAINT visited_places_trip_id_fkey;

CREATE TABLE calatorii
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    lastname    VARCHAR(255),
    email       VARCHAR(255),
    phone       VARCHAR(255),
    description VARCHAR(2000),
    image       VARCHAR(255),
    title       VARCHAR(255),
    CONSTRAINT pk_calatorii PRIMARY KEY (id)
);

DROP TABLE guides CASCADE;

DROP TABLE journal_entries CASCADE;

DROP TABLE roles CASCADE;

DROP TABLE tour_purchases CASCADE;

DROP TABLE tours CASCADE;

DROP TABLE trip_items CASCADE;

DROP TABLE trips CASCADE;

DROP TABLE user_points CASCADE;

DROP TABLE user_roles CASCADE;

DROP TABLE users CASCADE;

DROP TABLE visited_places CASCADE;